$(function() {
    $('.owl-carousel').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        dots:true,
        dotsEach:true,
        items:5,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
            },
            600:{
                items:2,
                nav:true,
                dots:true,
                dotsEach:true,
            },
            768:{
                items:2,
                nav:true,
                dots:true,
                dotsEach:true,
            },
            1000:{
                items:5,
                nav:true,
                dots:true,
                dotsEach:true,
            }
        }
    });
});